services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '15434:5432'
    volumes:
      - database:/var/lib/postgresql
  flyway:
    image: flyway/flyway
    command: -url=jdbc:postgresql://postgres:5432/mydatabase -user=myuser -password=secret -connectRetries=60 migrate
    volumes:
      - ./src/main/resources/migrations:/flyway/sql
    depends_on:
      - postgres
volumes:
  database: { }