spring:
  application:
    name: java-pr

  jmx:
    enabled: true

  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql

email:
  to: admin@admin.com

backup:
  directory: /home/sejapoe/dev/java/java-pr/backup